name: Prcing App Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: "tanulsangal"
          DOCKER_PASSWORD: "abcd@1234"
        run: docker login -u tanulsangal -p abcd@1234

      - name: Build Docker image
        run: docker build -f Dockerfile -t tanulsangal/pricingapp:latest . --network=host
      - name: Image push
        run: docker push tanulsangal/pricingapp:latest
